language: node_js
node_js:
- '10'
cache: npm
install:
- npm install -g @vue/cli
- npm install -g @vue/cli-service-global
before_script:
- npm install webpack
- npm install mocha
- yarn add @vue/cli-plugin-unit-mocha
script:
- yarn test:unit tests
before_deploy: yarn build --target wc --name datacite-components 'src/components/*.vue'
deploy:
  provider: npm
  email: kgarza@datacite.org
  edge: true
  skip_cleanup: true
  api_token:
    secure: uivr+a471utM6ptPqk9QQtqj074UMfokNwOUFxvSCiz0cPRPuzqkjFwyB9GBqhDjSaPyVKFZeOn0BZArtpjn1KKwfnI1hu5WFbyoH4sIGW+NKs4Bo8k5tGPHVM2FHMm4vj7pyC+Mc/zlu9y9trtGPF63kRbNxlX4EZ0NEIb83nwqpXFeVZgIs/LHvfd/x7ZRikX+fW+2arzLF4VWq5E6AZmmkr7T1RW+t8EzNjS2NrpjMCvDgEd+ybsFeT7wbvLrFhUADBmgMPEA5vBqoGcIuEw+ascKtnTjc7N+2rsUQUxZkUXqvIAX+3kBEetMrHmcbhL8z8qM8+Sb9rUTu/ns1NFS1IfeEosZ0WL9GGMMYfgzsMLvOWqoyGmMrNMLGQY4eCHSmBO5UvrnhQlDi+dz07ncqxrGJitL6GZdjYVtEhyFBLfV6GqIxze4QgEet3T8WQaLWz/w4uXt45Ub/wq+W19D9iI2tsCpfnTnBuJ0nfh1Nxb3z/Xn7Snhat8xBFJ32spFRBc0WCq9PUb5w6wNwj+isMabQDCiUGccmt6FUpHvMCnABA94EVRiT9FggLhvZb5+N2y/jir3CWqTnfE7TcdPrs8zgofOTRG3zUt5TxX3xHV445p1VsujDdOjvDO0qf/QnrgbvW4rrjBOVrD4kkPOZ5fOU7jLAkQdxmEEPU4=
  on:
    repo: datacite/datacite-components
    branch: master
  api_key:
    secure: q62p8YfiTP2xHjGOaTgSOqM43ffnaOAgfeLMN3Y9vzDH+7f5D+WwHckpwlDbaJvBJk54Dp4phpRqhXk1iLz1w/LgA+HMC+pk2UkJoL0FKlXgFo/nz8w4iXVWs9DptKQFaatS+xuWghv8hRXBg67wt6noG9USn3paVqM7imjkK3ZwIWwdVSEgxVSBwhkoyU0D79dAY5FFShsXD4kA2P//5Uz1Wx/xBk4q6EKBHeX04yAEEUADHlK/40uQ7+3BD12GetvLRAqOLZBtgWoQfGq98jtoDsMuWjZ4q0yjXn5+MDdc7qtDDQvhc+7MRZ+vdYniQ/wLS2UOUUnL/8dbGZaYy+/53apViiqLPXRsRPCIMVosYAXm1gsfyZeJMh9L+hN/cdsCPgyu74LD6NKmvwMapFH8YxGToqZr8EqkYeUcfokwOzS0p2qoLt+94SFBHUfesaiSgoZceXDpxW2jqzST8MrPnZ9naRergpHhWl8iyYjhZNUQ8Zp5Y6Df7kcGIHtNh1wgfVPCAoI+Abf4+NuwetvjQ6bYunY/LleMheB/OUyD/7p3oEWwI0EiiuVG+MPBZqG+GvA9PHdYHM2i6IuP5z7oLG1A124XNPXPKElJR7BBC3KpQmtrJK3r54pOwaNkiXKW8C0a1uuA5jY/CT5fDffHf/F1JBitdwQyIX/MEvo=
