language: node_js
node_js:
- 12.8.1
env:
- WEBPACK_VERSION=4 MOCHA_VERSION=4
- WEBPACK_VERSION=4 MOCHA_VERSION=5
cache: npm
install:
- npm install -g @vue/cli
- npm install -g @vue/cli-service-global
before_script:
- npm install webpack@$WEBPACK_VERSION
- npm install mocha@$MOCHA_VERSION
- yarn add @vue/cli-plugin-unit-mocha
script:
- echo "Success!"
# - yarn test:unit tests
before_deploy: vue build --target wc-async --name datacite-components 'src/components/*.vue'
deploy:
  provider: npm
  email: kj.garza@gmail.com
  skip_cleanup: true
  api_key:
    secure: sDv7QZYv1mkMwW7ADAudjGlEhuS9TshgqdKtfGXdsZcb9/AE7qSpO/xzrpotGdfu4Hcg3EDyrO7sJ8elbBF/0PCAMHCcaIKkw6D36uwOY8c3Sa+huDY8HXhQOHJDGNdzkBEjVQ28DzY1gBSx9Wj+HAZOp5UYnMjpRwqbSpotUP3d6lpCRCd8NspASJcgelzOW9nsUqWKyXRfm/waOGf0Pjtk3igreUJKw23FXKY4JiCNXKHAntQoOelUF1EwkhI0VXIh66j1JON8HgMv2nnxmkO3y5Ifhd5zYnelRkk1kYuUJDDKLvJdJkXkWSRx/5WANSYGE6zGP60j5LPEEbtZPjyNpejEhPBDfd3q2TLOxuLHaLyPDxvcCs0O7D5HYFUsC1vYgoZwCCfxwDCePJ4FDm/lGzsoJMd2fdr6LrUNe2XPvFEg+ScU30hWTJmDkTR3EPO+D9yNCyoY4ssmcAZR6QHCqs6HoBd875gSTg8B5SXPnE6mfzlE0HY9unwonm7XXv9e76htFnd9N3mwsZTUyOlmdLOL6tJjgzCjxgrKRhHxdMH2iNH3Y+TlxxrQh37c+07e6StcRHDer4J+OVC6TUinKSsWkND2cZeILy3itCquEedKAlYGuB6ZCu4XGYeBwJt+mBbRqoILRi8LWkQVCgnUPMesNitJyL99r5x8wN0=
  on:
    repo: kjgarza/datacite-components
    branch: master
