language: node_js
node_js:
- node
env:
- WEBPACK_VERSION=4 MOCHA_VERSION=4
- WEBPACK_VERSION=4 MOCHA_VERSION=5
cache: npm
install:
- npm install -g @vue/cli
- npm install -g @vue/cli-service-global
before_script:
- "npm install webpack@$WEBPACK_VERSION"
- "npm install mocha@$MOCHA_VERSION"
- yarn add @vue/cli-plugin-unit-mocha
script:
- echo "Success!"
# - yarn test:unit tests
before_deploy: yarn build --target wc-async --name datacite-components 'src/components/*.vue'
deploy:
  provider: npm
  email: kj.garza@gmail.com
  skip_cleanup: true
  api_key:
    secure: $GITHUB_TOKEN
  on:
    repo: kjgarza/datacite-components
    branch: master
